version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - echo "Building the Go app"
      - go build -o application
artifacts:
  files:
    - application